# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-24 03:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_auto_20160721_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricityBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('currency', models.CharField(choices=[('BPS', '£'), ('EUR', '€'), ('USD', '$')], default='BPS', max_length=3)),
                ('jan', models.FloatField(default=0, verbose_name='January')),
                ('feb', models.FloatField(default=0, verbose_name='February')),
                ('mar', models.FloatField(default=0, verbose_name='March')),
                ('apr', models.FloatField(default=0, verbose_name='April')),
                ('mai', models.FloatField(default=0, verbose_name='Mai')),
                ('jun', models.FloatField(default=0, verbose_name='June')),
                ('jul', models.FloatField(default=0, verbose_name='July')),
                ('aug', models.FloatField(default=0, verbose_name='August')),
                ('sep', models.FloatField(default=0, verbose_name='September')),
                ('oct', models.FloatField(default=0, verbose_name='October')),
                ('nov', models.FloatField(default=0, verbose_name='November')),
                ('dec', models.FloatField(default=0, verbose_name='December')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EnergyConsumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('jan', models.FloatField(default=0, verbose_name='January [kWh]')),
                ('feb', models.FloatField(default=0, verbose_name='February [kWh]')),
                ('mar', models.FloatField(default=0, verbose_name='March [kWh]')),
                ('apr', models.FloatField(default=0, verbose_name='April [kWh]')),
                ('mai', models.FloatField(default=0, verbose_name='Mai [kWh]')),
                ('jun', models.FloatField(default=0, verbose_name='June [kWh]')),
                ('jul', models.FloatField(default=0, verbose_name='July [kWh]')),
                ('aug', models.FloatField(default=0, verbose_name='August [kWh]')),
                ('sep', models.FloatField(default=0, verbose_name='September [kWh]')),
                ('oct', models.FloatField(default=0, verbose_name='October [kWh]')),
                ('nov', models.FloatField(default=0, verbose_name='November [kWh]')),
                ('dec', models.FloatField(default=0, verbose_name='December [kWh]')),
            ],
            options={
                'verbose_name_plural': 'Energy consumption',
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('type', models.IntegerField(choices=[(0, 'building'), (1, 'open space')], default=0)),
                ('roof', models.IntegerField(choices=[(0, 'flat'), (1, 'tilted')], default=0)),
            ],
            options={
                'verbose_name_plural': 'Facilities',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('country', models.CharField(blank=True, choices=[('GBR', 'United Kingdom'), ('USA', 'United States'), ('GER', 'Germany'), ('AUS', 'Australia')], help_text='Country of legal responsibility. Subsidies, energy prices, etc. depend on this selection.', max_length=3, null=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solar_projects', to='user.UserProfile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='energyconsumption',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='energy_consumption', to='manager.Project'),
        ),
        migrations.AddField(
            model_name='electricitybill',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='electricity_bills', to='manager.Project'),
        ),
    ]
