# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-28 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20160808_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='country',
            field=models.CharField(blank=True, choices=[('GBR', 'United Kingdom')], help_text='Country of legal responsibility. Subsidies, energy prices, etc. depend on this selection.', max_length=3, null=True),
        ),
    ]
