# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-12 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_auto_20160929_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='energyconsumption',
            name='project',
        ),
        migrations.DeleteModel(
            name='Facility',
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.IntegerField(choices=[(0, 'data collection'), (1, 'active'), (2, 'complete'), (3, 'complete')], default=0),
        ),
        migrations.AlterField(
            model_name='electricitybill',
            name='currency',
            field=models.CharField(choices=[('BPS', '£')], default='BPS', max_length=3),
        ),
        migrations.DeleteModel(
            name='EnergyConsumption',
        ),
    ]
