# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-12 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_auto_20161012_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricitybill',
            name='apr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='April'),
        ),
        migrations.AlterField(
            model_name='electricitybill',
            name='aug',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='August'),
        ),
        migrations.AlterField(
            model_name='electricitybill',
            name='dec',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='December'),
        ),
        migrations.AlterField(
            model_name='electricitybill',
            name='feb',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='February'),
        ),
        migrations.AlterField(
            model_name='electricitybill',
            name='jan',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='January'),
        ),
        migrations.AlterField(
            model_name='electricitybill',
            name='jul',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='July'),
        ),
        migrations.AlterField(
            model_name='electricitybill',
            name='jun',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='June'),
        ),
        migrations.AlterField(
            model_name='electricitybill',
            name='mai',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Mai'),
        ),
        migrations.AlterField(
            model_name='electricitybill',
            name='mar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='March'),
        ),
        migrations.AlterField(
            model_name='electricitybill',
            name='nov',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='November'),
        ),
        migrations.AlterField(
            model_name='electricitybill',
            name='oct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='October'),
        ),
        migrations.AlterField(
            model_name='electricitybill',
            name='sep',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='September'),
        ),
    ]
