# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-12 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_auto_20161012_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricitybill',
            name='provider',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='electricitybill',
            name='year',
            field=models.IntegerField(default=2016),
        ),
    ]
