# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-20 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_auto_20161020_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='status',
            field=models.IntegerField(choices=[(0, 'created'), (1, 'rejected'), (2, 'interested'), (3, 'processing'), (4, 'successful'), (5, 'denied')], default=0),
        ),
    ]
