# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-22 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0012_offer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='headline',
            field=models.CharField(default='change this', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offer',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='user.UserProfile', verbose_name='customer'),
        ),
    ]
