# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-28 22:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0013_auto_20161022_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='profile',
        ),
        migrations.AddField(
            model_name='offer',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='manager.Project', verbose_name='project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.IntegerField(choices=[(0, 'waiting for review'), (1, 'rejected'), (2, 'interested'), (3, 'processing'), (4, 'successful'), (5, 'unsuccessful')], default=0),
        ),
    ]
