# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-05 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0015_auto_20161028_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricitybill',
            name='year',
            field=models.IntegerField(default=2017),
        ),
    ]
