# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-08 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0016_auto_20170105_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.IntegerField(choices=[(0, 'data collection'), (1, 'active'), (2, 'paused'), (3, 'complete')], default=0),
        ),
    ]
