# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-10 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0017_auto_20170108_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='stage',
            field=models.IntegerField(choices=[(0, 'solar assessment'), (1, 'data collection'), (2, 'project design'), (3, 'permissions & approvals'), (4, 'project kick-off')], default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.IntegerField(choices=[(0, 'active'), (1, 'paused'), (2, 'complete')], default=0),
        ),
    ]
