# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-13 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0020_auto_20170410_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricitybill',
            name='file',
            field=models.FileField(help_text='Please upload a .pdf file if possible.', null=True, upload_to='uploads/electricity_bills/'),
        ),
    ]
