# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-13 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0021_auto_20170413_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricitybill',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
