# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-13 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0022_electricitybill_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricitybill',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
