# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-19 11:43
from __future__ import unicode_literals

from django.db import migrations
import private_storage.fields
import private_storage.storage.files


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0023_auto_20170413_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricitybill',
            name='private_file',
            field=private_storage.fields.PrivateFileField(help_text='Please upload a .pdf file if possible.', null=True, storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to='uploads/electricity_bills/'),
        ),
    ]
