# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-08 12:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0024_electricitybill_private_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electricitybill',
            name='file',
        ),
    ]
