# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-24 17:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0025_remove_electricitybill_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='country',
        ),
    ]
