# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-06 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='glossaryentry',
            name='published',
            field=models.BooleanField(default=False, verbose_name='published'),
        ),
        migrations.AddField(
            model_name='glossaryentry',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('revise', 'Revise'), ('ok', 'Ready')], default='draft', max_length=20, verbose_name='status'),
        ),
    ]
