# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-06 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20160806_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='glossaryentry',
            name='slug',
            field=models.SlugField(default='change this'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='glossaryentry',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('revise', 'Revise'), ('ready', 'Ready')], default='draft', max_length=20, verbose_name='status'),
        ),
    ]
