# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-14 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_auto_20160910_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='PressEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=140)),
                ('date', models.DateField()),
                ('link', models.URLField()),
            ],
        ),
    ]
