# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-12 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0009_auto_20170112_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='pressentry',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
