# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-13 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0010_pressentry_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pressentry',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
