# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-24 12:28
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SolarSystem',
            new_name='SolarEnergySystem',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='earnings_estimate',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='energy_estimate',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='savings_estimate',
        ),
        migrations.AddField(
            model_name='assessment',
            name='annual_earnings_estimate',
            field=models.FloatField(blank=True, null=True, verbose_name='Earnings estimate [£]'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='annual_energy_estimate',
            field=models.FloatField(blank=True, null=True, verbose_name='Energy estimate [kWh/year]'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='annual_savings_estimate',
            field=models.FloatField(blank=True, null=True, verbose_name='Savings estimate [£]'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
