# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 23:26
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0002_auto_20160724_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='monthly_earnings_estimates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=12),
        ),
        migrations.AddField(
            model_name='assessment',
            name='monthly_energy_estimates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=12),
        ),
        migrations.AddField(
            model_name='assessment',
            name='monthly_savings_estimates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=12),
        ),
    ]
