# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-11 11:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0005_exampleassessment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='solar.Assessment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
