# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-24 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0008_auto_20160917_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='system_capacity_estimate',
            field=models.FloatField(blank=True, null=True, verbose_name='system nameplate capacity estimate [kW]'),
        ),
    ]
