# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-28 18:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0009_assessment_system_capacity_estimate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exampleassessment',
            name='assessment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='solar.Assessment', verbose_name='example_assessment'),
        ),
    ]
