# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-28 18:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0010_auto_20160928_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exampleassessment',
            name='assessment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='example_assessment', to='solar.Assessment'),
        ),
    ]
