# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-28 23:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0013_auto_20160928_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exampleassessment',
            name='assessment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='example', to='solar.Assessment'),
        ),
        migrations.AlterField(
            model_name='exampleassessment',
            name='published',
            field=models.BooleanField(default=True, help_text='set to False to hide this example.'),
        ),
    ]
