# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-29 18:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_remove_project_notes'),
        ('solar', '0014_auto_20160928_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='facility',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='profile',
        ),
        migrations.AddField(
            model_name='assessment',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='manager.Project'),
        ),
    ]
