# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-10 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0015_auto_20160929_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='test',
            field=models.BooleanField(default=False, help_text='Use this flag to mark test assessments.'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='type',
            field=models.IntegerField(choices=[(0, 'uncategorized'), (1, 'private home'), (2, 'commercial building'), (3, 'public building')], default=0),
        ),
        migrations.AddField(
            model_name='assessment',
            name='useless',
            field=models.BooleanField(default=False, help_text='Use this flag to mark useless assessments.'),
        ),
    ]
