# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-12 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0016_auto_20161010_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='type',
            field=models.IntegerField(choices=[(0, '---'), (1, 'private home'), (2, 'commercial building'), (3, 'public building')], default=0),
        ),
    ]
