# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-15 16:13
from __future__ import unicode_literals

from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0017_auto_20161012_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='exampleassessment',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, help_text='Automatically cropped to the right dimensions.', null=True, upload_to='uploads/events/cover_images/'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='type',
            field=models.IntegerField(choices=[(0, '---'), (1, 'private home'), (2, 'commercial building'), (3, 'public building'), (4, 'open space')], default=0),
        ),
    ]
