# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-09 10:12
from __future__ import unicode_literals

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0018_auto_20161115_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exampleassessment',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, help_text='Automatically cropped to the right dimensions.', null=True, upload_to='uploads/examples/images/'),
        ),
    ]
