# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-23 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0019_auto_20161209_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='supervised',
            field=models.BooleanField(default=False, help_text='Use this flag to mark supervised assessments.'),
        ),
    ]
