# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-29 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0020_assessment_supervised'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='type',
            field=models.IntegerField(choices=[(0, '---'), (1, 'private home'), (2, 'commercial building'), (3, 'open space')], default=0),
        ),
    ]
