# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-12 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0022_auto_20170112_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='nrel_station_distance',
            field=models.FloatField(blank=True, null=True, verbose_name='station distance [km]'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='nrel_version',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='version'),
        ),
    ]
