# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-16 11:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0023_auto_20170112_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='user.Contact'),
        ),
    ]
