# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-20 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0024_auto_20170116_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='duplicate',
            field=models.BooleanField(default=False, help_text='Use this flag to mark duplicate assessments.'),
        ),
    ]
