# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-10 11:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0025_assessment_duplicate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SolarEnergySystem',
        ),
        migrations.DeleteModel(
            name='SolarPanel',
        ),
    ]
