# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-18 14:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0028_auto_20170413_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='location',
        ),
    ]
