# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-18 14:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0029_remove_assessment_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessment',
            old_name='location_object',
            new_name='location',
        ),
    ]
