# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-18 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0030_auto_20170518_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='alt_model',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
