# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-18 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0031_assessment_alt_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='alt_model',
        ),
        migrations.AddField(
            model_name='assessment',
            name='currency',
            field=models.CharField(default='GBP', max_length=3),
        ),
    ]
