# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-24 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0033_auto_20170519_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='currency',
            field=models.CharField(choices=[('GBP', '£'), ('INR', '₹')], default='GBP', max_length=3),
        ),
    ]
