# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-14 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0034_auto_20170524_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='mlreport',
            field=models.TextField(blank=True, null=True, verbose_name='mlreport'),
        ),
    ]
