# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-08 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20160721_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
