# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-26 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20160926_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='test',
            field=models.BooleanField(default=False, help_text='tick this to indicate test contacts.', verbose_name='test contact'),
        ),
    ]
