# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-09 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20161209_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='test',
            field=models.BooleanField(default=False),
        ),
    ]
