# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-29 18:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20161229_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactnotes',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Contact'),
        ),
    ]
