# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-29 18:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_contactnotes_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactnotes',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='user.Contact'),
        ),
    ]
