# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-29 18:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20161229_1851'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactNotes',
            new_name='ContactNote',
        ),
    ]
