# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-29 19:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_auto_20161229_1854'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'user profile'},
        ),
        migrations.AlterField(
            model_name='contactnote',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_contact_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contactnote',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_contact_notes', to=settings.AUTH_USER_MODEL),
        ),
    ]
