# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-08 12:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_auto_20170105_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='status_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
