# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-16 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_auto_20170108_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=255, null=True, verbose_name='phone number'),
        ),
    ]
