# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-19 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_auto_20170116_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='qualified_lead',
            field=models.BooleanField(default=False, verbose_name='qualified_lead'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='qualified_lead',
            field=models.BooleanField(default=False),
        ),
    ]
