# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-27 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_auto_20170119_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
