# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-31 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_auto_20170131_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='status',
            field=models.IntegerField(choices=[(0, 'contact created'), (1, 'contacted by team'), (2, 'offer processing'), (3, 'offer delivered'), (4, 'sale complete'), (5, 'no response'), (6, 'not interested'), (7, 'fake contact')], default=0),
        ),
    ]
