# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-20 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_auto_20170131_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='fake',
            field=models.BooleanField(default=False, verbose_name='fake'),
        ),
    ]
