# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-07 12:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_auto_20160721_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('requested', 'Support requested'), ('ongoing', 'Support ongoing'), ('hold', 'On hold'), ('done', 'Done')], default='requested', max_length=20)),
                ('assignee', models.CharField(blank=True, max_length=255, null=True)),
                ('automatic', models.BooleanField(default=False)),
                ('zopim_user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Contact')),
                ('required_actions', models.ManyToManyField(blank=True, null=True, to='support.SupportAction')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
