# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-07 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='required_actions',
            field=models.ManyToManyField(blank=True, to='support.SupportAction'),
        ),
    ]
