# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-07 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_callrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='callrequest',
            name='contacted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='callrequest',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
