# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-12 14:18
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nrel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodataerror',
            name='used_search_radius',
            field=models.FloatField(blank=True, null=True, verbose_name='used search radius [km]'),
        ),
        migrations.AlterField(
            model_name='nodataerror',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='geo location [deg]'),
        ),
    ]
