# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-19 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_remove_location_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='administrative_area_level_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='administrative_area_level_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
